//`define	BITS_PSUM_LOG	12
//`define	BITS_AC1	`BITS_SIP_DOT_ADDER+`N_ACT-1
//`define	BITS_AC2	`BITS_AC1+`N_WEIGHT-1+`BITS_PSUM_LOG
`define	N_ACT	8
`define	BITS_ACT	16
`define	N_WEIGHT	8
`define	BITS_WEIGHT	16
`define	N_DOT	8
`define	BITS_DOT	48
`define	PE_ROW	16
`define    PE_ARRAY 16
`define	N_MUL	17
`define	BITS_MUL	6
`define	N_BIAS	16
`define	LOG_PE_ROW	4
`define	BITS_PSUM_LOG	12
`define	BITS_PARALLEL	2
`define	BITS_SIP_DOT_ADDER	9	//BITS_MUL + (log_2_N_DOT-1)
`define	BITS_PSUM_SHIFT		23
`define	BITS_PSUM		28
